In [1]:
print('Hello world')

Hello world


In [2]:
import numpy as np

In [3]:
aar_1d = np.array([25,23,78])
print(aar_1d)
print(type(aar_1d))

[25 23 78]
<class 'numpy.ndarray'>


In [4]:
aar_2d = np.array([[25,23,78],[56,78,65]])
print(aar_2d)
print(type(aar_2d))

[[25 23 78]
 [56 78 65]]
<class 'numpy.ndarray'>


In [5]:
py_list = [1,3,5]
print("py_list multiplication", py_list*2)

np_list = np.array([1,3,5])
print("np_list multiplication", np_list*2)

py_list multiplication [1, 3, 5, 1, 3, 5]
np_list multiplication [ 2  6 10]


In [6]:
import time

start = time.time()
py_list = [i*2 for i in range(10000000)]
end = time.time()
print(f"\n operation time is {end-start}")


 operation time is 0.6727843284606934


In [7]:
start = time.time()
np_list = np.arange(10000000)*2
end = time.time()
print(f"\n operation time is {end-start}")


 operation time is 0.051180362701416016


In [8]:
zeroes = np.zeros((3,4))
print("zeroes array: \n", zeroes)

ones = np.ones((2,3))
print('one array: \n', ones)

zeroes array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
full = np.full((2,4), 7)
print('full array: \n', full)

full array: 
 [[7 7 7 7]
 [7 7 7 7]]


In [12]:
#vector

vector = np.array([35,8,78,90])
print("Vector ", vector)

matrix = np.array([[35,8,78,90],[56,78,33,74]])
print("matrix ", matrix)

tensor = np.array([[35,8,78,90],[56,78,33,74],[86,70,93,34],[37,85,78,80]])
print("tensor ", tensor)

Vector  [35  8 78 90]
matrix  [[35  8 78 90]
 [56 78 33 74]]
tensor  [[35  8 78 90]
 [56 78 33 74]
 [86 70 93 34]
 [37 85 78 80]]


In [ ]:
arr = np.array([[35,8,78,90],[56,78,33,74],[86,70,93,34],[37,85,78,80]])        
print("arr ", arr)

print("shape", arr.shape)
print("Dimension", arr.ndim)
print("size", arr.size)
print("dtype", arr.dtype)
print("astype", arr.astype)
print("congugate", arr.conjugate)




arr  [[35  8 78 90]
 [56 78 33 74]
 [86 70 93 34]
 [37 85 78 80]]
shape (4, 4)
Dimension 2
size 16
dtype int64
astype <built-in method astype of numpy.ndarray object at 0x0000023DBEC44E70>
congugate <built-in method conjugate of numpy.ndarray object at 0x0000023DBEC44E70>


In [22]:
arr = np.arange(39)
print("original",arr)

resh = arr.reshape((3,13))
print("reshape", resh)

flattened = resh.flatten()
print('flatten reshaped',flattened)

raveld = resh.ravel()
print('Raveled: ', raveld)


transpose = resh.T
print("transposed array ", transpose)


original [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]
reshape [[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24 25]
 [26 27 28 29 30 31 32 33 34 35 36 37 38]]
flatten reshaped [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]
Raveled:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]
transposed array  [[ 0 13 26]
 [ 1 14 27]
 [ 2 15 28]
 [ 3 16 29]
 [ 4 17 30]
 [ 5 18 31]
 [ 6 19 32]
 [ 7 20 33]
 [ 8 21 34]
 [ 9 22 35]
 [10 23 36]
 [11 24 37]
 [12 25 38]]
